version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
registry:
  jwt_expiration_time:
    value: 60

  timeout:
    value: 10

  read_timeout:
    value: 240
